language: go
install:
  - go get -a github.com/soundcloud/doozer
  - go get -a github.com/soundcloud/cotterpin
  - mkdir -p $GOPATH/src/github.com/soundcloud/glimpse
  - mv * $GOPATH/src/github.com/soundcloud/glimpse
  - mkdir -p $GOPATH/src/github.com/soundcloud
  - pushd $GOPATH/src/github.com/soundcloud
  - git clone git://github.com/soundcloud/doozerd.git
  - pushd doozerd
  - make compile
  - $GOPATH/bin/doozerd -hist=100 -w=false &> /dev/null &
  - sleep 3
  - nc -z 127.0.0.1 8046
  - popd
  - popd
script:
  - pushd $GOPATH/src/github.com/soundcloud/glimpse
  - go test -v
